--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigcrafter/Hydrogen
build-by-default: true
branches:
- main
projects:
  Hydrogen:
    path: ""
    model: virion
    type: library
    lint:
      phpstan: false
...
